# http://module-build.sourceforge.net/META-spec.html
#XXXXXXX This is a prototype!!!  It will change in the future!!! XXXXX#
name:         XML-XBEL
version:      1.0
version_from: lib/XML/XBEL.pm
installdirs:  site
requires:
    Date::Format:                  0
    Test::More:                    0
    XML::LibXML:                   1.58

distribution_type: module
generated_by: ExtUtils::MakeMaker version 6.17
